package agh.inzapp.inzynierka.models.enums;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static agh.inzapp.inzynierka.utils.FxmlUtils.getNameProperty;

public enum UniNames{
	// Base
	Date(getNameProperty("date"), getNameProperty("unit.date")),
	Time(getNameProperty("time"), getNameProperty("unit.time")),
	Flag(getNameProperty("Flag"), getNameProperty("unit.none")),
	Flag_P(getNameProperty("Flag_P"), getNameProperty("unit.none")),
	Flag_G(getNameProperty("Flag_G"), getNameProperty("unit.none")),
	Flag_E(getNameProperty("Flag_E"), getNameProperty("unit.none")),
	Flag_T(getNameProperty("Flag_T"), getNameProperty("unit.none")),
	Flag_A(getNameProperty("Flag_A"), getNameProperty("unit.none")),
	f(getNameProperty("f"), getNameProperty("unit.hz")),
	f_L1_min(getNameProperty("f.L1.min"), getNameProperty("unit.hz")),
	f_L1_max(getNameProperty("f.L1.max"), getNameProperty("unit.hz")),
	f_L1_avg(getNameProperty("f.L1.avg"), getNameProperty("unit.hz")),
	f_L2_min(getNameProperty("f.L2.min"), getNameProperty("unit.hz")),
	f_L2_max(getNameProperty("f.L2.max"), getNameProperty("unit.hz")),
	f_L2_avg(getNameProperty("f.L2.avg"), getNameProperty("unit.hz")),
	f_L3_min(getNameProperty("f.L3.min"), getNameProperty("unit.hz")),
	f_L3_max(getNameProperty("f.L3.max"), getNameProperty("unit.hz")),
	f_L3_avg(getNameProperty("f.L3.avg"), getNameProperty("unit.hz")),
	UL1_min(getNameProperty("UL1_min"), getNameProperty("unit.V")),
	UL1_max(getNameProperty("UL1_max"), getNameProperty("unit.V")),
	UL1_avg(getNameProperty("UL1_avg"), getNameProperty("unit.V")),
	UL2_min(getNameProperty("UL2_min"), getNameProperty("unit.V")),
	UL2_max(getNameProperty("UL2_max"), getNameProperty("unit.V")),
	UL2_avg(getNameProperty("UL2_avg"), getNameProperty("unit.V")),
	UL3_min(getNameProperty("UL3_min"), getNameProperty("unit.V")),
	UL3_max(getNameProperty("UL3_max"), getNameProperty("unit.V")),
	UL3_avg(getNameProperty("UL3_avg"), getNameProperty("unit.V")),
	U_NPE_min(getNameProperty("U_NPE_min"), getNameProperty("unit.V")),
	U_NPE_max(getNameProperty("U_NPE_max"), getNameProperty("unit.V")),
	U_NPE_avg(getNameProperty("U_NPE_avg"), getNameProperty("unit.V")),
	U12_min(getNameProperty("U12_min"), getNameProperty("unit.V")),
	U12_max(getNameProperty("U12_max"), getNameProperty("unit.V")),
	U12_avg(getNameProperty("U12_avg"), getNameProperty("unit.V")),
	U23_min(getNameProperty("U23_min"), getNameProperty("unit.V")),
	U23_max(getNameProperty("U23_max"), getNameProperty("unit.V")),
	U23_avg(getNameProperty("U23_avg"), getNameProperty("unit.V")),
	U31_min(getNameProperty("U31_min"), getNameProperty("unit.V")),
	U31_max(getNameProperty("U31_max"), getNameProperty("unit.V")),
	U31_avg(getNameProperty("U31_avg"), getNameProperty("unit.V")),
	IL1_min(getNameProperty("IL1_min"), getNameProperty("unit.A")),
	IL1_max(getNameProperty("IL1_max"), getNameProperty("unit.A")),
	IL1_avg(getNameProperty("IL1_avg"), getNameProperty("unit.A")),
	IL2_min(getNameProperty("IL2_min"), getNameProperty("unit.A")),
	IL2_max(getNameProperty("IL2_max"), getNameProperty("unit.A")),
	IL2_avg(getNameProperty("IL2_avg"), getNameProperty("unit.A")),
	IL3_min(getNameProperty("IL3_min"), getNameProperty("unit.A")),
	IL3_max(getNameProperty("IL3_max"), getNameProperty("unit.A")),
	IL3_avg(getNameProperty("IL3_avg"), getNameProperty("unit.A")),
	IN_min(getNameProperty("IN_min"), getNameProperty("unit.A")),
	IN_max(getNameProperty("IN_max"), getNameProperty("unit.A")),
	IN_avg(getNameProperty("IN_avg"), getNameProperty("unit.A")),
	Pst_U12(getNameProperty("Pst_U12"), getNameProperty("unit.none")),
	Pst_U23(getNameProperty("Pst_U23"), getNameProperty("unit.none")),
	Pst_U31(getNameProperty("Pst_U31"), getNameProperty("unit.none")),
	Plt_U12(getNameProperty("Plt_U12"), getNameProperty("unit.none")),
	Plt_U23(getNameProperty("Plt_U23"), getNameProperty("unit.none")),
	Plt_U31(getNameProperty("Plt_U31"), getNameProperty("unit.none")),
	Pst_UL1(getNameProperty("Pst_UL1"), getNameProperty("unit.none")),
	Pst_UL2(getNameProperty("Pst_UL2"), getNameProperty("unit.none")),
	Pst_UL3(getNameProperty("Pst_UL3"), getNameProperty("unit.none")),
	Plt_L1(getNameProperty("Plt_L1"), getNameProperty("unit.percentage")),
	Plt_L2(getNameProperty("Plt_L2"), getNameProperty("unit.percentage")),
	Plt_L3(getNameProperty("Plt_L3"), getNameProperty("unit.percentage")),
	U0_U1_min(getNameProperty("U0_U1_min"), getNameProperty("unit.percentage")),
	U0_U1_max(getNameProperty("U0_U1_max"), getNameProperty("unit.percentage")),
	U0_U1_avg(getNameProperty("U0_U1_avg"), getNameProperty("unit.percentage")),
	U2_U1_min(getNameProperty("U2_U1_min"), getNameProperty("unit.percentage")),
	U2_U1_max(getNameProperty("U2_U1_max"), getNameProperty("unit.percentage")),
	U2_U1_avg(getNameProperty("U2_U1_avg"), getNameProperty("unit.percentage")),
	U0_min_total(getNameProperty("U0_min"), getNameProperty("unit.V")),
	U0_max_total(getNameProperty("U0_max"), getNameProperty("unit.V")),
	U0_avg_total(getNameProperty("U0_avg"), getNameProperty("unit.V")),
	U1_min_total(getNameProperty("U1_min"), getNameProperty("unit.V")),
	U1_max_total(getNameProperty("U1_max"), getNameProperty("unit.V")),
	U1_avg_total(getNameProperty("U1_avg"), getNameProperty("unit.V")),
	U2_min_total(getNameProperty("U2_min"), getNameProperty("unit.V")),
	U2_max_total(getNameProperty("U2_max"), getNameProperty("unit.V")),
	U2_avg_total(getNameProperty("U2_avg"), getNameProperty("unit.V")),
	I0_I1_min(getNameProperty("I0_I1_min"), getNameProperty("unit.percentage")),
	I0_I1_max(getNameProperty("I0_I1_max"), getNameProperty("unit.percentage")),
	I0_I1_avg(getNameProperty("I0_I1_avg"), getNameProperty("unit.percentage")),
	I2_I1_min(getNameProperty("I2_I1_min"), getNameProperty("unit.percentage")),
	I2_I1_max(getNameProperty("I2_I1_max"), getNameProperty("unit.percentage")),
	I2_I1_avg(getNameProperty("I2_I1_avg"), getNameProperty("unit.percentage")),
	I0_min_total(getNameProperty("I0_min"), getNameProperty("unit.A")),
	I0_max_total(getNameProperty("I0_max"), getNameProperty("unit.A")),
	I0_avg_total(getNameProperty("I0_avg"), getNameProperty("unit.A")),
	I1_min_total(getNameProperty("I1_min"), getNameProperty("unit.A")),
	I1_max_total(getNameProperty("I1_max"), getNameProperty("unit.A")),
	I1_avg_total(getNameProperty("I1_avg"), getNameProperty("unit.A")),
	I2_min_total(getNameProperty("I2_min"), getNameProperty("unit.A")),
	I2_max_total(getNameProperty("I2_max"), getNameProperty("unit.A")),
	I2_avg_total(getNameProperty("I2_avg"), getNameProperty("unit.A")),
	CF_U_L1_avg(getNameProperty("CF.U.L1.avg"), getNameProperty("unit.none")),
	CF_U_L2_avg(getNameProperty("CF.U.L2.avg"), getNameProperty("unit.none")),
	CF_U_L3_avg(getNameProperty("CF.U.L3.avg"), getNameProperty("unit.none")),
	CF_U_NPE_avg(getNameProperty("CF.U.NPE.avg"), getNameProperty("unit.none")),
	CF_I_L1_avg(getNameProperty("CF.I.L1.avg"), getNameProperty("unit.none")),
	CF_I_L2_avg(getNameProperty("CF.I.L2.avg"), getNameProperty("unit.none")),
	CF_I_L3_avg(getNameProperty("CF.I.L3.avg"), getNameProperty("unit.none")),
	CF_I_N_avg(getNameProperty("CF.I.N.avg"), getNameProperty("unit.none")),
	THD_12(getNameProperty("THD_12"), getNameProperty("unit.percentage")),
	THD_23(getNameProperty("THD_23"), getNameProperty("unit.percentage")),
	THD_31(getNameProperty("THD_31"), getNameProperty("unit.percentage")),
	THD_L1(getNameProperty("THD_L1"), getNameProperty("unit.percentage")),
	THD_L2(getNameProperty("THD_L2"), getNameProperty("unit.percentage")),
	THD_L3(getNameProperty("THD_L3"), getNameProperty("unit.percentage")),
	H1_UL1(getNameProperty("H1_UL1"), getNameProperty("unit.percentage")),
	H2_UL1(getNameProperty("H2_UL1"), getNameProperty("unit.percentage")),
	H3_UL1(getNameProperty("H3_UL1"), getNameProperty("unit.percentage")),
	H4_UL1(getNameProperty("H4_UL1"), getNameProperty("unit.percentage")),
	H5_UL1(getNameProperty("H5_UL1"), getNameProperty("unit.percentage")),
	H6_UL1(getNameProperty("H6_UL1"), getNameProperty("unit.percentage")),
	H7_UL1(getNameProperty("H7_UL1"), getNameProperty("unit.percentage")),
	H8_UL1(getNameProperty("H8_UL1"), getNameProperty("unit.percentage")),
	H9_UL1(getNameProperty("H9_UL1"), getNameProperty("unit.percentage")),
	H10_UL1(getNameProperty("H10_UL1"), getNameProperty("unit.percentage")),
	H11_UL1(getNameProperty("H11_UL1"), getNameProperty("unit.percentage")),
	H12_UL1(getNameProperty("H12_UL1"), getNameProperty("unit.percentage")),
	H13_UL1(getNameProperty("H13_UL1"), getNameProperty("unit.percentage")),
	H14_UL1(getNameProperty("H14_UL1"), getNameProperty("unit.percentage")),
	H15_UL1(getNameProperty("H15_UL1"), getNameProperty("unit.percentage")),
	H16_UL1(getNameProperty("H16_UL1"), getNameProperty("unit.percentage")),
	H17_UL1(getNameProperty("H17_UL1"), getNameProperty("unit.percentage")),
	H18_UL1(getNameProperty("H18_UL1"), getNameProperty("unit.percentage")),
	H19_UL1(getNameProperty("H19_UL1"), getNameProperty("unit.percentage")),
	H20_UL1(getNameProperty("H20_UL1"), getNameProperty("unit.percentage")),
	H21_UL1(getNameProperty("H21_UL1"), getNameProperty("unit.percentage")),
	H22_UL1(getNameProperty("H22_UL1"), getNameProperty("unit.percentage")),
	H23_UL1(getNameProperty("H23_UL1"), getNameProperty("unit.percentage")),
	H24_UL1(getNameProperty("H24_UL1"), getNameProperty("unit.percentage")),
	H25_UL1(getNameProperty("H25_UL1"), getNameProperty("unit.percentage")),
	H26_UL1(getNameProperty("H26_UL1"), getNameProperty("unit.percentage")),
	H27_UL1(getNameProperty("H27_UL1"), getNameProperty("unit.percentage")),
	H28_UL1(getNameProperty("H28_UL1"), getNameProperty("unit.percentage")),
	H29_UL1(getNameProperty("H29_UL1"), getNameProperty("unit.percentage")),
	H30_UL1(getNameProperty("H30_UL1"), getNameProperty("unit.percentage")),
	H31_UL1(getNameProperty("H31_UL1"), getNameProperty("unit.percentage")),
	H32_UL1(getNameProperty("H32_UL1"), getNameProperty("unit.percentage")),
	H33_UL1(getNameProperty("H33_UL1"), getNameProperty("unit.percentage")),
	H34_UL1(getNameProperty("H34_UL1"), getNameProperty("unit.percentage")),
	H35_UL1(getNameProperty("H35_UL1"), getNameProperty("unit.percentage")),
	H36_UL1(getNameProperty("H36_UL1"), getNameProperty("unit.percentage")),
	H37_UL1(getNameProperty("H37_UL1"), getNameProperty("unit.percentage")),
	H38_UL1(getNameProperty("H38_UL1"), getNameProperty("unit.percentage")),
	H39_UL1(getNameProperty("H39_UL1"), getNameProperty("unit.percentage")),
	H40_UL1(getNameProperty("H40_UL1"), getNameProperty("unit.percentage")),
	H41_UL1(getNameProperty("H41_UL1"), getNameProperty("unit.percentage")),
	H42_UL1(getNameProperty("H42_UL1"), getNameProperty("unit.percentage")),
	H43_UL1(getNameProperty("H43_UL1"), getNameProperty("unit.percentage")),
	H44_UL1(getNameProperty("H44_UL1"), getNameProperty("unit.percentage")),
	H45_UL1(getNameProperty("H45_UL1"), getNameProperty("unit.percentage")),
	H46_UL1(getNameProperty("H46_UL1"), getNameProperty("unit.percentage")),
	H47_UL1(getNameProperty("H47_UL1"), getNameProperty("unit.percentage")),
	H48_UL1(getNameProperty("H48_UL1"), getNameProperty("unit.percentage")),
	H49_UL1(getNameProperty("H49_UL1"), getNameProperty("unit.percentage")),
	H50_UL1(getNameProperty("H50_UL1"), getNameProperty("unit.percentage")),
	H1_UL2(getNameProperty("H1_UL2"), getNameProperty("unit.percentage")),
	H2_UL2(getNameProperty("H2_UL2"), getNameProperty("unit.percentage")),
	H3_UL2(getNameProperty("H3_UL2"), getNameProperty("unit.percentage")),
	H4_UL2(getNameProperty("H4_UL2"), getNameProperty("unit.percentage")),
	H5_UL2(getNameProperty("H5_UL2"), getNameProperty("unit.percentage")),
	H6_UL2(getNameProperty("H6_UL2"), getNameProperty("unit.percentage")),
	H7_UL2(getNameProperty("H7_UL2"), getNameProperty("unit.percentage")),
	H8_UL2(getNameProperty("H8_UL2"), getNameProperty("unit.percentage")),
	H9_UL2(getNameProperty("H9_UL2"), getNameProperty("unit.percentage")),
	H10_UL2(getNameProperty("H10_UL2"), getNameProperty("unit.percentage")),
	H11_UL2(getNameProperty("H11_UL2"), getNameProperty("unit.percentage")),
	H12_UL2(getNameProperty("H12_UL2"), getNameProperty("unit.percentage")),
	H13_UL2(getNameProperty("H13_UL2"), getNameProperty("unit.percentage")),
	H14_UL2(getNameProperty("H14_UL2"), getNameProperty("unit.percentage")),
	H15_UL2(getNameProperty("H15_UL2"), getNameProperty("unit.percentage")),
	H16_UL2(getNameProperty("H16_UL2"), getNameProperty("unit.percentage")),
	H17_UL2(getNameProperty("H17_UL2"), getNameProperty("unit.percentage")),
	H18_UL2(getNameProperty("H18_UL2"), getNameProperty("unit.percentage")),
	H19_UL2(getNameProperty("H19_UL2"), getNameProperty("unit.percentage")),
	H20_UL2(getNameProperty("H20_UL2"), getNameProperty("unit.percentage")),
	H21_UL2(getNameProperty("H21_UL2"), getNameProperty("unit.percentage")),
	H22_UL2(getNameProperty("H22_UL2"), getNameProperty("unit.percentage")),
	H23_UL2(getNameProperty("H23_UL2"), getNameProperty("unit.percentage")),
	H24_UL2(getNameProperty("H24_UL2"), getNameProperty("unit.percentage")),
	H25_UL2(getNameProperty("H25_UL2"), getNameProperty("unit.percentage")),
	H26_UL2(getNameProperty("H26_UL2"), getNameProperty("unit.percentage")),
	H27_UL2(getNameProperty("H27_UL2"), getNameProperty("unit.percentage")),
	H28_UL2(getNameProperty("H28_UL2"), getNameProperty("unit.percentage")),
	H29_UL2(getNameProperty("H29_UL2"), getNameProperty("unit.percentage")),
	H30_UL2(getNameProperty("H30_UL2"), getNameProperty("unit.percentage")),
	H31_UL2(getNameProperty("H31_UL2"), getNameProperty("unit.percentage")),
	H32_UL2(getNameProperty("H32_UL2"), getNameProperty("unit.percentage")),
	H33_UL2(getNameProperty("H33_UL2"), getNameProperty("unit.percentage")),
	H34_UL2(getNameProperty("H34_UL2"), getNameProperty("unit.percentage")),
	H35_UL2(getNameProperty("H35_UL2"), getNameProperty("unit.percentage")),
	H36_UL2(getNameProperty("H36_UL2"), getNameProperty("unit.percentage")),
	H37_UL2(getNameProperty("H37_UL2"), getNameProperty("unit.percentage")),
	H38_UL2(getNameProperty("H38_UL2"), getNameProperty("unit.percentage")),
	H39_UL2(getNameProperty("H39_UL2"), getNameProperty("unit.percentage")),
	H40_UL2(getNameProperty("H40_UL2"), getNameProperty("unit.percentage")),
	H41_UL2(getNameProperty("H41_UL2"), getNameProperty("unit.percentage")),
	H42_UL2(getNameProperty("H42_UL2"), getNameProperty("unit.percentage")),
	H43_UL2(getNameProperty("H43_UL2"), getNameProperty("unit.percentage")),
	H44_UL2(getNameProperty("H44_UL2"), getNameProperty("unit.percentage")),
	H45_UL2(getNameProperty("H45_UL2"), getNameProperty("unit.percentage")),
	H46_UL2(getNameProperty("H46_UL2"), getNameProperty("unit.percentage")),
	H47_UL2(getNameProperty("H47_UL2"), getNameProperty("unit.percentage")),
	H48_UL2(getNameProperty("H48_UL2"), getNameProperty("unit.percentage")),
	H49_UL2(getNameProperty("H49_UL2"), getNameProperty("unit.percentage")),
	H50_UL2(getNameProperty("H50_UL2"), getNameProperty("unit.percentage")),
	H1_UL3(getNameProperty("H1_UL3"), getNameProperty("unit.percentage")),
	H2_UL3(getNameProperty("H2_UL3"), getNameProperty("unit.percentage")),
	H3_UL3(getNameProperty("H3_UL3"), getNameProperty("unit.percentage")),
	H4_UL3(getNameProperty("H4_UL3"), getNameProperty("unit.percentage")),
	H5_UL3(getNameProperty("H5_UL3"), getNameProperty("unit.percentage")),
	H6_UL3(getNameProperty("H6_UL3"), getNameProperty("unit.percentage")),
	H7_UL3(getNameProperty("H7_UL3"), getNameProperty("unit.percentage")),
	H8_UL3(getNameProperty("H8_UL3"), getNameProperty("unit.percentage")),
	H9_UL3(getNameProperty("H9_UL3"), getNameProperty("unit.percentage")),
	H10_UL3(getNameProperty("H10_UL3"), getNameProperty("unit.percentage")),
	H11_UL3(getNameProperty("H11_UL3"), getNameProperty("unit.percentage")),
	H12_UL3(getNameProperty("H12_UL3"), getNameProperty("unit.percentage")),
	H13_UL3(getNameProperty("H13_UL3"), getNameProperty("unit.percentage")),
	H14_UL3(getNameProperty("H14_UL3"), getNameProperty("unit.percentage")),
	H15_UL3(getNameProperty("H15_UL3"), getNameProperty("unit.percentage")),
	H16_UL3(getNameProperty("H16_UL3"), getNameProperty("unit.percentage")),
	H17_UL3(getNameProperty("H17_UL3"), getNameProperty("unit.percentage")),
	H18_UL3(getNameProperty("H18_UL3"), getNameProperty("unit.percentage")),
	H19_UL3(getNameProperty("H19_UL3"), getNameProperty("unit.percentage")),
	H20_UL3(getNameProperty("H20_UL3"), getNameProperty("unit.percentage")),
	H21_UL3(getNameProperty("H21_UL3"), getNameProperty("unit.percentage")),
	H22_UL3(getNameProperty("H22_UL3"), getNameProperty("unit.percentage")),
	H23_UL3(getNameProperty("H23_UL3"), getNameProperty("unit.percentage")),
	H24_UL3(getNameProperty("H24_UL3"), getNameProperty("unit.percentage")),
	H25_UL3(getNameProperty("H25_UL3"), getNameProperty("unit.percentage")),
	H26_UL3(getNameProperty("H26_UL3"), getNameProperty("unit.percentage")),
	H27_UL3(getNameProperty("H27_UL3"), getNameProperty("unit.percentage")),
	H28_UL3(getNameProperty("H28_UL3"), getNameProperty("unit.percentage")),
	H29_UL3(getNameProperty("H29_UL3"), getNameProperty("unit.percentage")),
	H30_UL3(getNameProperty("H30_UL3"), getNameProperty("unit.percentage")),
	H31_UL3(getNameProperty("H31_UL3"), getNameProperty("unit.percentage")),
	H32_UL3(getNameProperty("H32_UL3"), getNameProperty("unit.percentage")),
	H33_UL3(getNameProperty("H33_UL3"), getNameProperty("unit.percentage")),
	H34_UL3(getNameProperty("H34_UL3"), getNameProperty("unit.percentage")),
	H35_UL3(getNameProperty("H35_UL3"), getNameProperty("unit.percentage")),
	H36_UL3(getNameProperty("H36_UL3"), getNameProperty("unit.percentage")),
	H37_UL3(getNameProperty("H37_UL3"), getNameProperty("unit.percentage")),
	H38_UL3(getNameProperty("H38_UL3"), getNameProperty("unit.percentage")),
	H39_UL3(getNameProperty("H39_UL3"), getNameProperty("unit.percentage")),
	H40_UL3(getNameProperty("H40_UL3"), getNameProperty("unit.percentage")),
	H41_UL3(getNameProperty("H41_UL3"), getNameProperty("unit.percentage")),
	H42_UL3(getNameProperty("H42_UL3"), getNameProperty("unit.percentage")),
	H43_UL3(getNameProperty("H43_UL3"), getNameProperty("unit.percentage")),
	H44_UL3(getNameProperty("H44_UL3"), getNameProperty("unit.percentage")),
	H45_UL3(getNameProperty("H45_UL3"), getNameProperty("unit.percentage")),
	H46_UL3(getNameProperty("H46_UL3"), getNameProperty("unit.percentage")),
	H47_UL3(getNameProperty("H47_UL3"), getNameProperty("unit.percentage")),
	H48_UL3(getNameProperty("H48_UL3"), getNameProperty("unit.percentage")),
	H49_UL3(getNameProperty("H49_UL3"), getNameProperty("unit.percentage")),
	H50_UL3(getNameProperty("H50_UL3"), getNameProperty("unit.percentage")),
	K_L1_avg(getNameProperty("K.L1.avg"), getNameProperty("unit.none")),
	K_L2_avg(getNameProperty("K.L2.avg"), getNameProperty("unit.none")),
	K_L3_avg(getNameProperty("K.L3.avg"), getNameProperty("unit.none")),
	K_N_avg(getNameProperty("K.n.avg"), getNameProperty("unit.none")),
	PF_L1_min(getNameProperty("PF.L1.min"), getNameProperty("unit.none")),
	PF_L1_max(getNameProperty("PF.L1.max"), getNameProperty("unit.none")),
	PF_L1_avg(getNameProperty("PF_L1_avg"), getNameProperty("unit.none")),
	PF_L2_min(getNameProperty("PF.L2.min"), getNameProperty("unit.none")),
	PF_L2_max(getNameProperty("PF.L2.max"), getNameProperty("unit.none")),
	PF_L2_avg(getNameProperty("PF_L2_avg"), getNameProperty("unit.none")),
	PF_L3_min(getNameProperty("PF.L3.min"), getNameProperty("unit.none")),
	PF_L3_max(getNameProperty("PF.L3.max"), getNameProperty("unit.none")),
	PF_L3_avg(getNameProperty("PF_L3_avg"), getNameProperty("unit.none")),
	PF_total_min(getNameProperty("PF.total.min"), getNameProperty("unit.none")),
	PF_total_max(getNameProperty("PF.total.max"), getNameProperty("unit.none")),
	PF_total_avg(getNameProperty("PF.total.avg"), getNameProperty("unit.none")),
	PF_total_abs(getNameProperty("PF_total_abs"), getNameProperty("unit.none")),
	cos_phi(getNameProperty("cos_phi"), getNameProperty("unit.none")),
	tan_phi(getNameProperty("tan_phi"), getNameProperty("unit.none")),
	cos_phi_L1_avg(getNameProperty("cos.phi.L1.avg"), getNameProperty("unit.none")),
	cos_phi_L2_avg(getNameProperty("cos.phi.L2.avg"), getNameProperty("unit.none")),
	cos_phi_L3_avg(getNameProperty("cos.phi.L3.avg"), getNameProperty("unit.none")),
	cos_phi_total_avg(getNameProperty("cos.phi.total.avg"), getNameProperty("unit.none")),
	tan_phi_L1_Lplus_avg(getNameProperty("tan.phi.L1.Lplus.avg"), getNameProperty("unit.none")),
	tan_phi_L2_Lplus_avg(getNameProperty("tan.phi.L2.Lplus.avg"), getNameProperty("unit.none")),
	tan_phi_L3_Lplus_avg(getNameProperty("tan.phi.L3.Lplus.avg"), getNameProperty("unit.none")),
	tan_phi_total_Lplus_avg(getNameProperty("tan.phi.total.Lplus.avg"), getNameProperty("unit.none")),
	tan_phi_L1_Cmin_avg(getNameProperty("tan.phi.L1.Cmin.avg"), getNameProperty("unit.none")),
	tan_phi_L2_Cmin_avg(getNameProperty("tan.phi.L2.Cmin.avg"), getNameProperty("unit.none")),
	tan_phi_L3_Cmin_avg(getNameProperty("tan.phi.L3.Cmin.avg"), getNameProperty("unit.none")),
	tan_phi_total_Cmin_avg(getNameProperty("tan.phi.total.Cmin.avg"), getNameProperty("unit.none")),
	tan_phi_L1_Lmin_avg(getNameProperty("tan.phi.L1.Lmin.avg"), getNameProperty("unit.none")),
	tan_phi_L2_Lmin_avg(getNameProperty("tan.phi.L2.Lmin.avg"), getNameProperty("unit.none")),
	tan_phi_L3_Lmin_avg(getNameProperty("tan.phi.L3.Lmin.avg"), getNameProperty("unit.none")),
	tan_phi_total_Lmin_avg(getNameProperty("tan.phi.total.Lmin.avg"), getNameProperty("unit.none")),
	tan_phi_L1_Cplus_avg(getNameProperty("tan.phi.L1.Cplus.avg"), getNameProperty("unit.none")),
	tan_phi_L2_Cplus_avg(getNameProperty("tan.phi.L2.Cplus.avg"), getNameProperty("unit.none")),
	tan_phi_L3_Cplus_avg(getNameProperty("tan.phi.L3.Cplus.avg"), getNameProperty("unit.none")),
	tan_phi_total_Cplus_avg(getNameProperty("tan.phi.total.Cplus.avg"), getNameProperty("unit.none")),
	P_L1_min(getNameProperty("P_L1_min"), getNameProperty("unit.kW")),
	P_L1_max(getNameProperty("P_L1_max"), getNameProperty("unit.kW")),
	P_L1_avg(getNameProperty("P_L1_avg"), getNameProperty("unit.kW")),
	P_L2_min(getNameProperty("P_L2_min"), getNameProperty("unit.kW")),
	P_L2_max(getNameProperty("P_L2_max"), getNameProperty("unit.kW")),
	P_L2_avg(getNameProperty("P_L2_avg"), getNameProperty("unit.kW")),
	P_L3_min(getNameProperty("P_L3_min"), getNameProperty("unit.kW")),
	P_L3_max(getNameProperty("P_L3_max"), getNameProperty("unit.kW")),
	P_L3_avg(getNameProperty("P_L3_avg"), getNameProperty("unit.kW")),
	P_total_min(getNameProperty("P.total.min"), getNameProperty("unit.kW")),
	P_total_max(getNameProperty("P.total.max"), getNameProperty("unit.kW")),
	P_total_avg(getNameProperty("P.total.avg"), getNameProperty("unit.kW")),
	P_total_abs(getNameProperty("P_abs"), getNameProperty("unit.kW")),
	P_plus_L1_avg(getNameProperty("P.plus.L1.avg"), getNameProperty("unit.kW")),
	P_plus_L2_avg(getNameProperty("P.plus.L2.avg"), getNameProperty("unit.kW")),
	P_plus_L3_avg(getNameProperty("P.plus.L3.avg"), getNameProperty("unit.kW")),
	P_plus_total_avg(getNameProperty("P.plus.total.avg"), getNameProperty("unit.kW")),
	P_min_L1_avg(getNameProperty("P.min.L1.avg"), getNameProperty("unit.kW")),
	P_min_L2_avg(getNameProperty("P.min.L2.avg"), getNameProperty("unit.kW")),
	P_min_L3_avg(getNameProperty("P.min.L3.avg"), getNameProperty("unit.kW")),
	P_min_total_avg(getNameProperty("P.min.total.avg"), getNameProperty("unit.kW")),
	Q_L1_min(getNameProperty("Q_L1_min"), getNameProperty("unit.kVar")),
	Q_L1_max(getNameProperty("Q_L1_max"), getNameProperty("unit.kVar")),
	Q_L1_avg(getNameProperty("Q_L1_avg"), getNameProperty("unit.kVar")),
	Q_L2_min(getNameProperty("Q_L2_min"), getNameProperty("unit.kVar")),
	Q_L2_max(getNameProperty("Q_L2_max"), getNameProperty("unit.kVar")),
	Q_L2_avg(getNameProperty("Q_L2_avg"), getNameProperty("unit.kVar")),
	Q_L3_min(getNameProperty("Q_L3_min"), getNameProperty("unit.kVar")),
	Q_L3_max(getNameProperty("Q_L3_max"), getNameProperty("unit.kVar")),
	Q_L3_avg(getNameProperty("Q_L3_avg"), getNameProperty("unit.kVar")),
	Q_total_max(getNameProperty("Q_max"), getNameProperty("unit.kVar")),
	Q_total_min(getNameProperty("Q_min"), getNameProperty("unit.kVar")),
	Q_total_avg(getNameProperty("Q.total.avg"), getNameProperty("unit.kVar")),
	Sn_L1_avg(getNameProperty("Sn.L1.avg"), getNameProperty("unit.kVA")),
	Sn_L2_avg(getNameProperty("Sn.L2.avg"), getNameProperty("unit.kVA")),
	Sn_L3_avg(getNameProperty("Sn.L3.avg"), getNameProperty("unit.kVA")),
	Sn_total(getNameProperty("Sn.total"), getNameProperty("unit.kVA")),
	S_L1_min(getNameProperty("S_L1_min"), getNameProperty("unit.kVA")),
	S_L1_max(getNameProperty("S_L1_max"), getNameProperty("unit.kVA")),
	S_L1_avg(getNameProperty("S_L1_avg"), getNameProperty("unit.kVA")),
	S_L2_min(getNameProperty("S_L2_min"), getNameProperty("unit.kVA")),
	S_L2_max(getNameProperty("S_L2_max"), getNameProperty("unit.kVA")),
	S_L2_avg(getNameProperty("S_L2_avg"), getNameProperty("unit.kVA")),
	S_L3_min(getNameProperty("S_L3_min"), getNameProperty("unit.kVA")),
	S_L3_max(getNameProperty("S_L3_max"), getNameProperty("unit.kVA")),
	S_L3_avg(getNameProperty("S_L3_avg"), getNameProperty("unit.kVA")),
	S_total_min(getNameProperty("S_total_min"), getNameProperty("unit.kVA")),
	S_total_max(getNameProperty("S_total_max"), getNameProperty("unit.kVA")),
	S_total_avg(getNameProperty("S_total_avg"), getNameProperty("unit.kVA")),
	NONE("none", "[-]");
	private final String uniName;
	private final String unit;

	private static final List<UniNames> L1 = new ArrayList<>(Arrays.asList(
			H2_UL1, H3_UL1, H4_UL1, H5_UL1, H6_UL1, H7_UL1, H8_UL1, H9_UL1, H10_UL1,
			H11_UL1, H12_UL1, H13_UL1, H14_UL1, H15_UL1, H16_UL1, H17_UL1, H18_UL1, H19_UL1, H20_UL1,
			H21_UL1, H22_UL1, H23_UL1, H24_UL1, H25_UL1, H26_UL1, H27_UL1, H28_UL1, H29_UL1, H30_UL1,
			H31_UL1, H32_UL1, H33_UL1, H34_UL1, H35_UL1, H36_UL1, H37_UL1, H38_UL1, H39_UL1, H40_UL1,
			H41_UL1, H42_UL1, H43_UL1, H44_UL1, H45_UL1, H46_UL1, H47_UL1, H48_UL1, H49_UL1, H50_UL1));
	
	private static List<UniNames> L2 = new ArrayList<>(Arrays.asList(
			H2_UL2, H3_UL2, H4_UL2, H5_UL2, H6_UL2, H7_UL2, H8_UL2, H9_UL2, H10_UL2,
			H11_UL2, H12_UL2, H13_UL2, H14_UL2, H15_UL2, H16_UL2, H17_UL2, H18_UL2, H19_UL2, H20_UL2,
			H21_UL2, H22_UL2, H23_UL2, H24_UL2, H25_UL2, H26_UL2, H27_UL2, H28_UL2, H29_UL2, H30_UL2,
			H31_UL2, H32_UL2, H33_UL2, H34_UL2, H35_UL2, H36_UL2, H37_UL2, H38_UL2, H39_UL2, H40_UL2,
			H41_UL2, H42_UL2, H43_UL2, H44_UL2, H45_UL2, H46_UL2, H47_UL2, H48_UL2, H49_UL2, H50_UL2));
	private static List<UniNames> L3 = new ArrayList<>(Arrays.asList(
			H2_UL3, H3_UL3, H4_UL3, H5_UL3, H6_UL3, H7_UL3, H8_UL3, H9_UL3, H10_UL3,
			H11_UL3, H12_UL3, H13_UL3, H14_UL3, H15_UL3, H16_UL3, H17_UL3, H18_UL3, H19_UL3, H20_UL3,
			H21_UL3, H22_UL3, H23_UL3, H24_UL3, H25_UL3, H26_UL3, H27_UL3, H28_UL3, H29_UL3, H30_UL3,
			H31_UL3, H32_UL3, H33_UL3, H34_UL3, H35_UL3, H36_UL3, H37_UL3, H38_UL3, H39_UL3, H40_UL3,
			H41_UL3, H42_UL3, H43_UL3, H44_UL3, H45_UL3, H46_UL3, H47_UL3, H48_UL3, H49_UL3, H50_UL3));

	private static final List<UniNames> Q = new ArrayList<>(Arrays.asList(
			Q_L1_avg, Q_L2_avg, Q_L3_avg, Q_L1_max, Q_L2_max, Q_L3_max, Q_L1_min, Q_L2_min, Q_L3_min, Q_total_avg, Q_total_min, Q_total_max
	));

	private static final List<UniNames> S = new ArrayList<>(Arrays.asList(
			S_total_avg, Sn_total, S_L1_avg, S_L2_avg, S_L3_avg, Sn_L3_avg, Sn_L2_avg, Sn_L2_avg, S_L1_min, S_L1_max, S_L2_min, S_L2_max, S_L3_min, S_L3_max
	));

	private static final List<UniNames> P = new ArrayList<>(Arrays.asList(
			P_total_avg, P_total_max, P_total_min, P_L1_avg, P_L2_avg, P_L3_avg, P_L1_min, P_L2_min, P_L3_min, P_L1_max, P_L2_max, P_L3_max
	));

	private static final List<UniNames> HARMONICS = new ArrayList<>(Arrays.asList(THD_L1, THD_L2, THD_L3, THD_12, THD_23, THD_31,
			H1_UL1, H2_UL1, H3_UL1, H4_UL1, H5_UL1, H6_UL1, H7_UL1, H8_UL1, H9_UL1, H10_UL1,
			H11_UL1, H12_UL1, H13_UL1, H14_UL1, H15_UL1, H16_UL1, H17_UL1, H18_UL1, H19_UL1, H20_UL1,
			H21_UL1, H22_UL1, H23_UL1, H24_UL1, H25_UL1, H26_UL1, H27_UL1, H28_UL1, H29_UL1, H30_UL1,
			H31_UL1, H32_UL1, H33_UL1, H34_UL1, H35_UL1, H36_UL1, H37_UL1, H38_UL1, H39_UL1, H40_UL1,
			H41_UL1, H42_UL1, H43_UL1, H44_UL1, H45_UL1, H46_UL1, H47_UL1, H48_UL1, H49_UL1, H50_UL1,
			H1_UL2, H2_UL2, H3_UL2, H4_UL2, H5_UL2, H6_UL2, H7_UL2, H8_UL2, H9_UL2, H10_UL2,
			H11_UL2, H12_UL2, H13_UL2, H14_UL2, H15_UL2, H16_UL2, H17_UL2, H18_UL2, H19_UL2, H20_UL2,
			H21_UL2, H22_UL2, H23_UL2, H24_UL2, H25_UL2, H26_UL2, H27_UL2, H28_UL2, H29_UL2, H30_UL2,
			H31_UL2, H32_UL2, H33_UL2, H34_UL2, H35_UL2, H36_UL2, H37_UL2, H38_UL2, H39_UL2, H40_UL2,
			H41_UL2, H42_UL2, H43_UL2, H44_UL2, H45_UL2, H46_UL2, H47_UL2, H48_UL2, H49_UL2, H50_UL2,
			H1_UL3, H2_UL3, H3_UL3, H4_UL3, H5_UL3, H6_UL3, H7_UL3, H8_UL3, H9_UL3, H10_UL3,
			H11_UL3, H12_UL3, H13_UL3, H14_UL3, H15_UL3, H16_UL3, H17_UL3, H18_UL3, H19_UL3, H20_UL3,
			H21_UL3, H22_UL3, H23_UL3, H24_UL3, H25_UL3, H26_UL3, H27_UL3, H28_UL3, H29_UL3, H30_UL3,
			H31_UL3, H32_UL3, H33_UL3, H34_UL3, H35_UL3, H36_UL3, H37_UL3, H38_UL3, H39_UL3, H40_UL3,
			H41_UL3, H42_UL3, H43_UL3, H44_UL3, H45_UL3, H46_UL3, H47_UL3, H48_UL3, H49_UL3, H50_UL3));

	private static final List<UniNames> HARMONICS_ENOUGH = new ArrayList<>(Arrays.asList(
			THD_L1, THD_L2, THD_L3,
			H1_UL1, H2_UL1, H3_UL1, H4_UL1, H5_UL1, H6_UL1, H7_UL1, H8_UL1, H9_UL1, H10_UL1,
			H11_UL1, H12_UL1, H13_UL1, H14_UL1, H15_UL1, H16_UL1, H17_UL1, H18_UL1, H19_UL1, H20_UL1,
			H21_UL1, H22_UL1, H23_UL1, H24_UL1, H25_UL1,
			H1_UL2, H2_UL2, H3_UL2, H4_UL2, H5_UL2, H6_UL2, H7_UL2, H8_UL2, H9_UL2, H10_UL2,
			H11_UL2, H12_UL2, H13_UL2, H14_UL2, H15_UL2, H16_UL2, H17_UL2, H18_UL2, H19_UL2, H20_UL2,
			H21_UL2, H22_UL2, H23_UL2, H24_UL2, H25_UL2,
			H1_UL3, H2_UL3, H3_UL3, H4_UL3, H5_UL3, H6_UL3, H7_UL3, H8_UL3, H9_UL3, H10_UL3,
			H11_UL3, H12_UL3, H13_UL3, H14_UL3, H15_UL3, H16_UL3, H17_UL3, H18_UL3, H19_UL3, H20_UL3,
			H21_UL3, H22_UL3, H23_UL3, H24_UL3, H25_UL3));

	private static final List<UniNames> NORMAL_ENOUGH = new ArrayList<>(Arrays.asList(
			UL1_avg, UL2_avg, UL3_avg, U2_U1_avg, Plt_L1, Plt_L2, Plt_L3));
	UniNames(String uniName, String unit) {
		this.uniName = uniName;
		this.unit = unit;
	}

	public String getUnit() {
		return unit;
	}

	public String getUniName() { return uniName;}
	@Override
	public String toString() {
		return this.uniName;
	}

	public static List<UniNames> getPowerLineHarmonicNames(int i) throws IllegalStateException {
		List<UniNames> list;
		switch (i){
			case 1 -> list = L1;
			case 2 -> list = L2;
			case 3 -> list = L3;
			default -> throw new IllegalStateException("Unexpected value: " + i);
		}
		return list;
	}

	public static List<UniNames> getL1HarmoNames()  {
		return L1;
	}

	public static List<UniNames> getL2HarmoNames()  {
		return L2;
	}

	public static List<UniNames> getL3HarmoNames()  {
		return L3;
	}

	public static List<UniNames> getQ(){return Q;}

	public static List<UniNames> getS(){return S;}
	public static List<UniNames> getP(){return P;}
	public static List<UniNames> getHarmonics(){return HARMONICS;}
	public static List<UniNames> getHarmonicsEnough(){return HARMONICS_ENOUGH;}
	public static List<UniNames> getNormalEnough() {
		return NORMAL_ENOUGH;
	}
}
