package agh.inzapp.inzynierka.enums;

import java.util.stream.Stream;

import static agh.inzapp.inzynierka.utils.FxmlUtils.getInternalizedPropertyByKey;

public enum UniNames implements UnitaryNames{
	// Base
	Date(getInternalizedPropertyByKey("column.date"), getInternalizedPropertyByKey("unit.date")),
	Time(getInternalizedPropertyByKey("column.time"), getInternalizedPropertyByKey("unit.time")),
	Flag(getInternalizedPropertyByKey("column.Flag"), getInternalizedPropertyByKey("unit.none")),
	Flag_P(getInternalizedPropertyByKey("column.Flag_P"), getInternalizedPropertyByKey("unit.none")),
	Flag_G(getInternalizedPropertyByKey("column.Flag_G"), getInternalizedPropertyByKey("unit.none")),
	Flag_E(getInternalizedPropertyByKey("column.Flag_E"), getInternalizedPropertyByKey("unit.none")),
	Flag_T(getInternalizedPropertyByKey("column.Flag_T"), getInternalizedPropertyByKey("unit.none")),
	Flag_A(getInternalizedPropertyByKey("column.Flag_A"), getInternalizedPropertyByKey("unit.none")),
	U12_avg(getInternalizedPropertyByKey("column.U12_avg"), getInternalizedPropertyByKey("unit.V")),
	U23_avg(getInternalizedPropertyByKey("column.U23_avg"), getInternalizedPropertyByKey("unit.V")),
	U31_avg(getInternalizedPropertyByKey("column.U31_avg"), getInternalizedPropertyByKey("unit.V")),
	U12_max(getInternalizedPropertyByKey("column.U12_max"), getInternalizedPropertyByKey("unit.V")),
	U23_max(getInternalizedPropertyByKey("column.U23_max"), getInternalizedPropertyByKey("unit.V")),
	U31_max(getInternalizedPropertyByKey("column.U31_max"), getInternalizedPropertyByKey("unit.V")),
	U12_min(getInternalizedPropertyByKey("column.U12_min"), getInternalizedPropertyByKey("unit.V")),
	U23_min(getInternalizedPropertyByKey("column.U23_min"), getInternalizedPropertyByKey("unit.V")),
	U31_min(getInternalizedPropertyByKey("column.U31_min"), getInternalizedPropertyByKey("unit.V")),
	UL1_avg(getInternalizedPropertyByKey("column.UL1_avg"), getInternalizedPropertyByKey("unit.V")),
	UL2_avg(getInternalizedPropertyByKey("column.UL2_avg"), getInternalizedPropertyByKey("unit.V")),
	UL3_avg(getInternalizedPropertyByKey("column.UL3_avg"), getInternalizedPropertyByKey("unit.V")),
	UL1_max(getInternalizedPropertyByKey("column.UL1_max"), getInternalizedPropertyByKey("unit.V")),
	UL2_max(getInternalizedPropertyByKey("column.UL2_max"), getInternalizedPropertyByKey("unit.V")),
	UL3_max(getInternalizedPropertyByKey("column.UL3_max"), getInternalizedPropertyByKey("unit.V")),
	UL1_min(getInternalizedPropertyByKey("column.UL1_min"), getInternalizedPropertyByKey("unit.V")),
	UL2_min(getInternalizedPropertyByKey("column.UL2_min"), getInternalizedPropertyByKey("unit.V")),
	UL3_min(getInternalizedPropertyByKey("column.UL3_min"), getInternalizedPropertyByKey("unit.V")),
	U_NPE_avg(getInternalizedPropertyByKey("column.U_NPE_avg"), getInternalizedPropertyByKey("unit.V")),
	U_NPE_max(getInternalizedPropertyByKey("column.U_NPE_max"), getInternalizedPropertyByKey("unit.V")),
	U_NPE_min(getInternalizedPropertyByKey("column.U_NPE_min"), getInternalizedPropertyByKey("unit.V")),
	IL1_avg(getInternalizedPropertyByKey("column.IL1_avg"), getInternalizedPropertyByKey("unit.A")),
	IL2_avg(getInternalizedPropertyByKey("column.IL2_avg"), getInternalizedPropertyByKey("unit.A")),
	IL3_avg(getInternalizedPropertyByKey("column.IL3_avg"), getInternalizedPropertyByKey("unit.A")),
	IN_avg(getInternalizedPropertyByKey("column.IN_avg"), getInternalizedPropertyByKey("unit.A")),
	IL1_max(getInternalizedPropertyByKey("column.IL1_max"), getInternalizedPropertyByKey("unit.A")),
	IL2_max(getInternalizedPropertyByKey("column.IL2_max"), getInternalizedPropertyByKey("unit.A")),
	IL3_max(getInternalizedPropertyByKey("column.IL3_max"), getInternalizedPropertyByKey("unit.A")),
	IN_max(getInternalizedPropertyByKey("column.IN_max"), getInternalizedPropertyByKey("unit.A")),
	IL1_min(getInternalizedPropertyByKey("column.IL1_min"), getInternalizedPropertyByKey("unit.A")),
	IL2_min(getInternalizedPropertyByKey("column.IL2_min"), getInternalizedPropertyByKey("unit.A")),
	IL3_min(getInternalizedPropertyByKey("column.IL3_min"), getInternalizedPropertyByKey("unit.A")),
	IN_min(getInternalizedPropertyByKey("column.IN_min"), getInternalizedPropertyByKey("unit.A")),
	U0_avg(getInternalizedPropertyByKey("column.U0_avg"), getInternalizedPropertyByKey("unit.V")),
	U1_avg(getInternalizedPropertyByKey("column.U1_avg"), getInternalizedPropertyByKey("unit.V")),
	U2_avg(getInternalizedPropertyByKey("column.U2_avg"), getInternalizedPropertyByKey("unit.V")),
	U0_max(getInternalizedPropertyByKey("column.U0_max"), getInternalizedPropertyByKey("unit.V")),
	U1_max(getInternalizedPropertyByKey("column.U1_max"), getInternalizedPropertyByKey("unit.V")),
	U2_max(getInternalizedPropertyByKey("column.U2_max"), getInternalizedPropertyByKey("unit.V")),
	U0_min(getInternalizedPropertyByKey("column.U0_min"), getInternalizedPropertyByKey("unit.V")),
	U1_min(getInternalizedPropertyByKey("column.U1_min"), getInternalizedPropertyByKey("unit.V")),
	U2_min(getInternalizedPropertyByKey("column.U2_min"), getInternalizedPropertyByKey("unit.V")),
	I0_avg(getInternalizedPropertyByKey("column.I0_avg"), getInternalizedPropertyByKey("unit.A")),
	I1_avg(getInternalizedPropertyByKey("column.I1_avg"), getInternalizedPropertyByKey("unit.A")),
	I2_avg(getInternalizedPropertyByKey("column.I2_avg"), getInternalizedPropertyByKey("unit.A")),
	I0_max(getInternalizedPropertyByKey("column.I0_max"), getInternalizedPropertyByKey("unit.A")),
	I1_max(getInternalizedPropertyByKey("column.I1_max"), getInternalizedPropertyByKey("unit.A")),
	I2_max(getInternalizedPropertyByKey("column.I2_max"), getInternalizedPropertyByKey("unit.A")),
	I0_min(getInternalizedPropertyByKey("column.I0_min"), getInternalizedPropertyByKey("unit.A")),
	I1_min(getInternalizedPropertyByKey("column.I1_min"), getInternalizedPropertyByKey("unit.A")),
	I2_min(getInternalizedPropertyByKey("column.I2_min"), getInternalizedPropertyByKey("unit.A")),
	Pst_U12(getInternalizedPropertyByKey("column.Pst_U12"), getInternalizedPropertyByKey("unit.none")),
	Pst_U23(getInternalizedPropertyByKey("column.Pst_U23"), getInternalizedPropertyByKey("unit.none")),
	Pst_U31(getInternalizedPropertyByKey("column.Pst_U31"), getInternalizedPropertyByKey("unit.none")),
	Plt_U12(getInternalizedPropertyByKey("column.Plt_U12"), getInternalizedPropertyByKey("unit.none")),
	Plt_U23(getInternalizedPropertyByKey("column.Plt_U23"), getInternalizedPropertyByKey("unit.none")),
	Plt_U31(getInternalizedPropertyByKey("column.Plt_U31"), getInternalizedPropertyByKey("unit.none")),
	Pst_UL1(getInternalizedPropertyByKey("column.Pst_UL1"), getInternalizedPropertyByKey("unit.none")),
	Pst_UL2(getInternalizedPropertyByKey("column.Pst_UL2"), getInternalizedPropertyByKey("unit.none")),
	Pst_UL3(getInternalizedPropertyByKey("column.Pst_UL3"), getInternalizedPropertyByKey("unit.none")),
	Plt_L1(getInternalizedPropertyByKey("column.Plt_L1"), getInternalizedPropertyByKey("unit.percentage")),
	Plt_L2(getInternalizedPropertyByKey("column.Plt_L2"), getInternalizedPropertyByKey("unit.percentage")),
	Plt_L3(getInternalizedPropertyByKey("column.Plt_L3"), getInternalizedPropertyByKey("unit.percentage")),
	Unbalanced_Voltage(getInternalizedPropertyByKey("column.Unbalanced_Voltage"), getInternalizedPropertyByKey("unit.percentage")),
	Unbalanced_Current(getInternalizedPropertyByKey("column.Unbalanced_Current"), getInternalizedPropertyByKey("unit.percentage")),
	f(getInternalizedPropertyByKey("column.f"), getInternalizedPropertyByKey("unit.hz")),
	cos_phi(getInternalizedPropertyByKey("column.cos_phi"), getInternalizedPropertyByKey("unit.none")),
	tan_phi(getInternalizedPropertyByKey("column.tan_phi"), getInternalizedPropertyByKey("unit.none")),
	PF_total(getInternalizedPropertyByKey("column.PF_total"), getInternalizedPropertyByKey("unit.none")),
	PF_total_abs(getInternalizedPropertyByKey("column.PF_total_abs"), getInternalizedPropertyByKey("unit.none")),
	PF_L1_avg(getInternalizedPropertyByKey("column.PF_L1_avg"), getInternalizedPropertyByKey("unit.none")),
	PF_L2_avg(getInternalizedPropertyByKey("column.PF_L2_avg"), getInternalizedPropertyByKey("unit.none")),
	PF_L3_avg(getInternalizedPropertyByKey("column.PF_L3_avg"), getInternalizedPropertyByKey("unit.none")),
	P_total(getInternalizedPropertyByKey("column.P_total"), getInternalizedPropertyByKey("unit.kW")),
	P_abs(getInternalizedPropertyByKey("column.P_abs"), getInternalizedPropertyByKey("unit.kW")),
	P_max(getInternalizedPropertyByKey("column.P_max"), getInternalizedPropertyByKey("unit.kW")),
	P_min(getInternalizedPropertyByKey("column.P_min"), getInternalizedPropertyByKey("unit.kW")),
	P_L1_avg(getInternalizedPropertyByKey("column.P_L1_avg"), getInternalizedPropertyByKey("unit.kW")),
	P_L2_avg(getInternalizedPropertyByKey("column.P_L2_avg"), getInternalizedPropertyByKey("unit.kW")),
	P_L3_avg(getInternalizedPropertyByKey("column.P_L3_avg"), getInternalizedPropertyByKey("unit.kW")),
	P_L1_max(getInternalizedPropertyByKey("column.P_L1_max"), getInternalizedPropertyByKey("unit.kW")),
	P_L2_max(getInternalizedPropertyByKey("column.P_L2_max"), getInternalizedPropertyByKey("unit.kW")),
	P_L3_max(getInternalizedPropertyByKey("column.P_L3_max"), getInternalizedPropertyByKey("unit.kW")),
	P_L1_min(getInternalizedPropertyByKey("column.P_L1_min"), getInternalizedPropertyByKey("unit.kW")),
	P_L2_min(getInternalizedPropertyByKey("column.P_L2_min"), getInternalizedPropertyByKey("unit.kW")),
	P_L3_min(getInternalizedPropertyByKey("column.P_L3_min"), getInternalizedPropertyByKey("unit.kW")),
	S_total(getInternalizedPropertyByKey("column.S_total"), getInternalizedPropertyByKey("unit.kVA")),
	S_max(getInternalizedPropertyByKey("column.S_max"), getInternalizedPropertyByKey("unit.kVA")),
	S_min(getInternalizedPropertyByKey("column.S_min"), getInternalizedPropertyByKey("unit.kVA")),
	S_L1_avg(getInternalizedPropertyByKey("column.S_L1_avg"), getInternalizedPropertyByKey("unit.kVA")),
	S_L2_avg(getInternalizedPropertyByKey("column.S_L2_avg"), getInternalizedPropertyByKey("unit.kVA")),
	S_L3_avg(getInternalizedPropertyByKey("column.S_L3_avg"), getInternalizedPropertyByKey("unit.kVA")),
	S_L1_max(getInternalizedPropertyByKey("column.S_L1_max"), getInternalizedPropertyByKey("unit.kVA")),
	S_L2_max(getInternalizedPropertyByKey("column.S_L2_max"), getInternalizedPropertyByKey("unit.kVA")),
	S_L3_max(getInternalizedPropertyByKey("column.S_L3_max"), getInternalizedPropertyByKey("unit.kVA")),
	S_L1_min(getInternalizedPropertyByKey("column.S_L1_min"), getInternalizedPropertyByKey("unit.kVA")),
	S_L2_min(getInternalizedPropertyByKey("column.S_L2_min"), getInternalizedPropertyByKey("unit.kVA")),
	S_L3_min(getInternalizedPropertyByKey("column.S_L3_min"), getInternalizedPropertyByKey("unit.kVA")),
	Q_total(getInternalizedPropertyByKey("column.Q_total"), getInternalizedPropertyByKey("unit.kVar")),
	Q_max(getInternalizedPropertyByKey("column.Q_max"), getInternalizedPropertyByKey("unit.kVar")),
	Q_min(getInternalizedPropertyByKey("column.Q_min"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L1_avg(getInternalizedPropertyByKey("column.Q_L1_avg"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L2_avg(getInternalizedPropertyByKey("column.Q_L2_avg"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L3_avg(getInternalizedPropertyByKey("column.Q_L3_avg"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L1_max(getInternalizedPropertyByKey("column.Q_L1_max"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L2_max(getInternalizedPropertyByKey("column.Q_L2_max"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L3_max(getInternalizedPropertyByKey("column.Q_L3_max"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L1_min(getInternalizedPropertyByKey("column.Q_L1_min"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L2_min(getInternalizedPropertyByKey("column.Q_L2_min"), getInternalizedPropertyByKey("unit.kVar")),
	Q_L3_min(getInternalizedPropertyByKey("column.Q_L3_min"), getInternalizedPropertyByKey("unit.kVar")),
	U0_U1_avg(getInternalizedPropertyByKey("column.U0_U1_avg"), getInternalizedPropertyByKey("unit.percentage")),
	U0_U1_min(getInternalizedPropertyByKey("column.U0_U1_min"), getInternalizedPropertyByKey("unit.percentage")),
	U0_U1_max(getInternalizedPropertyByKey("column.U0_U1_max"), getInternalizedPropertyByKey("unit.percentage")),
	U2_U1_avg(getInternalizedPropertyByKey("column.U2_U1_avg"), getInternalizedPropertyByKey("unit.percentage")),
	U2_U1_min(getInternalizedPropertyByKey("column.U2_U1_min"), getInternalizedPropertyByKey("unit.percentage")),
	U2_U1_max(getInternalizedPropertyByKey("column.U2_U1_max"), getInternalizedPropertyByKey("unit.percentage")),
	I0_I1_avg(getInternalizedPropertyByKey("column.I0_I1_avg"), getInternalizedPropertyByKey("unit.percentage")),
	I0_I1_min(getInternalizedPropertyByKey("column.I0_I1_min"), getInternalizedPropertyByKey("unit.percentage")),
	I0_I1_max(getInternalizedPropertyByKey("column.I0_I1_max"), getInternalizedPropertyByKey("unit.percentage")),
	I2_I1_avg(getInternalizedPropertyByKey("column.I2_I1_avg"), getInternalizedPropertyByKey("unit.percentage")),
	I2_I1_min(getInternalizedPropertyByKey("column.I2_I1_min"), getInternalizedPropertyByKey("unit.percentage")),
	I2_I1_max(getInternalizedPropertyByKey("column.I2_I1_max"), getInternalizedPropertyByKey("unit.percentage"));

	private final String uniName;
	private final String unit;

	UniNames(String uniName, String unit) {
		this.uniName = uniName;
		this.unit = unit;
	}

	public String getUnit() {
		return unit;
	}
//	public String getUniName() { return uniName;}

	@Override
	public String toString() {
		return this.uniName;
	}
}
